tree:
  minitree:
  eventNumber: "eventNumber" # Keep field for verification purposes
  PV_: "PV."
  l_: "lep."
  lbar_: "lbar."
  llbar_: "llbar."
  jets_: "jetsAK4_selected."
  allJets_: "jetsAK4."
  PuppiMET_: "PuppiMET."
  # l_pt: "lep.corr_pt"
  # l_uncorrected_pt: "lep.Pt"
  # l_phi: "lep.Phi"
  # l_eta: "lep.Eta"
  # l_mass: "lep.M"
  # l_pdgId: "lep.PdgId"
  # lbar_pt: "lbar.corr_pt"
  # lbar_uncorrected_pt: "lbar.Pt"
  # lbar_phi: "lbar.Phi"
  # lbar_eta: "lbar.Eta"
  # lbar_mass: "lbar.M"
  # lbar_pdgId: "lbar.PdgId"
  # jets_pt: "jetsAK4_selected.Pt"
  # jets_phi: "jetsAK4_selected.Phi"
  # jets_eta: "jetsAK4_selected.Eta"
  # jets_mass: "jetsAK4_selected.M"
  # jets_deltaRlep: "jetsAK4_selected.DeltaR_lep"
  # jets_deltaRlbar: "jetsAK4_selected.DeltaR_lbar"
  # allJets_pt: "jetsAK4.Pt"
  # allJets_phi: "jetsAK4.Phi"
  # allJets_eta: "jetsAK4.Eta"
  # allJets_mass: "jetsAK4.M"
  # bs_pt: "bJetsAK4.Pt"
  # bs_phi: "bJetsAK4.Phi"
  # bs_eta: "bJetsAK4.Eta"
  # bs_mass: "bJetsAK4.M"
  # bs_BShapeWeight: "bJetsAK4.bShapeWeight"
  # bs_BKinfFitWeight: "bJetsAK4.bKinfFitWeight"
  # b_pt: "bjet.Pt"
  # b_phi: "bjet.Phi"
  # b_eta: "bjet.Eta"
  # b_mass: "bjet.M"
  # bbar_pt: "bbarjet.Pt"
  # bbar_phi: "bbarjet.Phi"
  # bbar_eta: "bbarjet.Eta"
  # bbar_mass: "bbarjet.M"
  # allJets_BtagRobustParTAK4B: "jetsAK4.BtagRobustParTAK4B"
  # allJets_BtagRobustParTAK4CvB: "jetsAK4.BtagRobustParTAK4CvB"
  # allJets_BtagRobustParTAK4CvL: "jetsAK4.BtagRobustParTAK4CvL"
  # allJets_BtagRobustParTAK4QG: "jetsAK4.BtagRobustParTAK4QG"
  # allJets_BtagDeepFlavB: "jetsAK4.BtagDeepFlavB"
  # allJets_BtagDeepFlavCvB: "jetsAK4.BtagDeepFlavCvB"
  # allJets_BtagDeepFlavCvL: "jetsAK4.BtagDeepFlavCvL"
  # allJets_BtagDeepFlavQG: "jetsAK4.BtagDeepFlavQG"
  # allJets_BtagPNetB: "jetsAK4.BtagPNetB"
  # allJets_BtagPNetCvB: "jetsAK4.BtagPNetCvB"
  # allJets_BtagPNetCvL: "jetsAK4.BtagPNetCvL"
  # allJets_BtagPNetQvG: "jetsAK4.BtagPNetQvG"
  # allJets_BtagPNetTauVJet: "jetsAK4.BtagPNetTauVJet"
  # jets_BtagRobustParTAK4B: "jetsAK4_selected.BtagRobustParTAK4B"
  # jets_BtagRobustParTAK4CvB: "jetsAK4_selected.BtagRobustParTAK4CvB"
  # jets_BtagRobustParTAK4CvL: "jetsAK4_selected.BtagRobustParTAK4CvL"
  # jets_BtagRobustParTAK4QG: "jetsAK4_selected.BtagRobustParTAK4QG"
  # jets_BtagDeepFlavB: "jetsAK4_selected.BtagDeepFlavB"
  # jets_BtagDeepFlavCvB: "jetsAK4_selected.BtagDeepFlavCvB"
  # jets_BtagDeepFlavCvL: "jetsAK4_selected.BtagDeepFlavCvL"
  # jets_BtagDeepFlavQG: "jetsAK4_selected.BtagDeepFlavQG"
  # jets_BtagPNetB: "jetsAK4_selected.BtagPNetB"
  # jets_BtagPNetCvB: "jetsAK4_selected.BtagPNetCvB"
  # jets_BtagPNetCvL: "jetsAK4_selected.BtagPNetCvL"
  # jets_BtagPNetQvG: "jetsAK4_selected.BtagPNetQvG"
  # jets_BtagPNetTauVJet: "jetsAK4_selected.BtagPNetTauVJet"
  # jets_BshapeWeight: "jetsAK4_selected.bShapeWeight"
  # jets_BKinfFitWeight: "jetsAK4_selected.bKinfFitWeight"
  # met_pt: "metPuppi.Pt"
  # met_phi: "metPuppi.Phi"
  # met_mass: "met.M"
  # ttbar_pt: "ttbar.Pt"
  # ttbar_phi: "ttbar.Phi"
  # ttbar_eta: "ttbar.Eta"
  # ttbar_mass: "ttbar.M"
  # llbar_pt: "llbar.Pt"
  # llbar_phi: "llbar.Phi"
  # llbar_eta: "llbar.Eta"
  # llbar_mass: "llbar.M"
  trueLevelWeight: "trueLevelWeight"
  eventWeight: "eventWeight"
  lepEIDWeight: "lep.electronIDWeight"
  lbarEIDWeight: "lbar.electronIDWeight"
  lepMuIDWeight: "lep.muonIDWeight"
  lbarMuIDWeight: "lbar.muonIDWeight"
  lepMuIsoWeight: "lep.muonIsoWeight"
  lbarMuIsoWeight: "lbar.muonIsoWeight"
  puWeight: "puWeight"
  genWeight: "weightGenerator"