tree:
  eventNumber: "event" # Keep field for verification purposes
  PV: "PV."
  l: "lep."
  lbar: "lbar."
  llbar: "llbar."
  jets: "Jet_selected."
  allJets: "Jet."
  PuppiMET: "PuppiMET."
  electron: "Electron."
  muon: "Muon."
  tau: "Tau."
  tauProd: "TauProd."
  trueLevelWeight: "trueLevelWeight"
  eventWeight: "eventWeight"
  lepEIDWeight: "lep.electronIDWeight"
  lbarEIDWeight: "lbar.electronIDWeight"
  lepMuIDWeight: "lep.muonIDWeight"
  lbarMuIDWeight: "lbar.muonIDWeight"
  lepMuIsoWeight: "lep.muonIsoWeight"
  lbarMuIsoWeight: "lbar.muonIsoWeight"
  puWeight: "puWeight"
  genWeight: "genWeight"
  # eftWeight: "eftWeight."