Weights:
  eventWeight:
    - "genWeight"
    - "puWeight"
    - "lep.electronIDWeight"
    - "lbar.electronIDWeight"
    - "lep.muonIDWeight"
    - "lbar.muonIDWeight"
    - "lep.muonIsoWeight"
    - "lbar.muonIsoWeight"
    - "lep.tauEFakeWeight"
    - "lbar.tauEFakeWeight"
    - "lep.tauMuFakeWeight"
    - "lbar.tauMuFakeWeight"
    - "lep.tauJetFakeWeight"
    - "lbar.tauJetFakeWeight"
  trueLevelWeight:
    - "genWeight"