MC:
  '2024':
    TTto2L2Nu:
      DAS:
        - /TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v3/NANOAODSIM
      xroot: root://eos.cms.rcac.purdue.edu//
    TTtoLNu2Q:
      DAS:
        - /TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
      xroot: root://eos.cms.rcac.purdue.edu//
    # DYto2L_1J_Mll50_PTll100to200:
    #   DAS:
    #     - /DYto2L-2Jets_Bin-1J-MLL-50-PTLL-100to200_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/RunIII2024Summer24NanoAODv15-150X_mcRun3_2024_realistic_v2-v2/NANOAODSIM
    #   xroot: root://eos.cms.rcac.purdue.edu//